version: 0.2

env:
  shell: bash
  variables:
    TF_APPLY_ACTION: "destroy"
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - tf_version=$TERRAFORM_VERSION
      - wget https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - echo "Terraform version:" && terraform --version

  pre_build:
    commands:
      - echo "Checking AWS credentials..."
      - aws sts get-caller-identity
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
  build:
    commands:
      - echo "Starting Infrastructure Deployment..."
      - cd $CODEBUILD_SRC_DIR
      - echo "Initializing Terraform..."
      - terraform init -backend-config=backend.tfvars -input=false
      - echo "Running Terraform changes..."
      - terraform destroy --auto-approve -var-file=dev.tfvars
      - echo "Terraform changes completed successfully!"

  post_build:
    commands:
      - echo "Infrastructure deployed via Terraform"
