version: 0.2
env:
  shell: bash
  variables:
    TF_APPLY_ACTION: "apply"
phases:
  install:
    runtime-versions:
      python: 3.13.5
    commands:
      - tf_version=$TERRAFORM_VERSION
      - wget https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - aws sts get-caller-identity
      - terraform --version
  build:
    commands:
      # Navigate to the root where main.tf is located
      - cd $CODEBUILD_SRC_DIR

      # Initialize Terraform with backend.tfvars and tfvars for passing variables
      - terraform init -backend-config=backend.tfvars -input=false

      # Run terraform plan to preview changes (with variables passed via tfvars)
      - terraform plan -var-file=dev.tfvars

      # Apply Terraform changes (with variables passed via tfvars)
      - terraform $TF_APPLY_ACTION --auto-approve -var-file=dev.tfvars
