version: 0.0
os: linux
files:
  - source: /src
    destination: /home/ec2-user
file_exists_behaviour: OVERWRITE
permissions:
- object: /home/ec2-user/scripts
  owner: ec2-user
  group: ec2-user
  mode: 777
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 120
      runas: ec2-user