version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies if any.."
  build:
    commands:
      - echo "Preparing artifact for CodeDeploy"
      # Copy appspec.yml from deployment/ to artifact root
      - cp deployment/appspec.yml .
      # Copy deployment scripts to root-level scripts folder
      - cp -r deployment/scripts ./scripts
      # Copy source code
      - cp -r src ./src
artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - src/**/*
